# Generated by Django 3.1.7 on 2021-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField()),
                ('name', models.TextField()),
                ('args', models.TextField(null=True)),
                ('stdout', models.TextField(null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_command_admin_call',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('app', models.TextField()),
            ],
            options={
                'db_table': 'django_command_admin_command',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['name'], name='django_comm_name_024f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['app'], name='django_comm_app_0aaf36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('app', 'name')},
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['name'], name='django_comm_name_25691c_idx'),
        ),
    ]
